DROP TABLE IF EXISTS veggies;

CREATE TABLE veggies (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    row_spacing INTEGER NOT NULL,
    plant_spacing INTEGER NOT NULL,
    germination_days INTEGER NOT NULL,
    thinning_days INTEGER,
    harvest_days INTEGER NOT NULL
);
