DROP TYPE IF EXISTS event_type;
DROP TABLE IF EXISTS events;

CREATE TYPE event_type AS ENUM (
    'planting', 'thinning', 'watering', 'weeding', 'harvesting'
);

CREATE TABLE events (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES users(id) NOT NULL,
    event_type event_type NOT NULL,
    event_date DATE NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT false,
    notes TEXT NOT NULL
);